// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/secmon-lab/lycaon/pkg/domain/model"
)

type CreateTaskInput struct {
	IncidentID  string  `json:"incidentId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	AssigneeID  *string `json:"assigneeId,omitempty"`
}

type IncidentConnection struct {
	Edges      []*IncidentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type IncidentEdge struct {
	Node   *model.Incident `json:"node"`
	Cursor string          `json:"cursor"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type UpdateIncidentInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type UpdateTaskInput struct {
	Title       *string           `json:"title,omitempty"`
	Description *string           `json:"description,omitempty"`
	Status      *model.TaskStatus `json:"status,omitempty"`
	AssigneeID  *string           `json:"assigneeId,omitempty"`
}
